import { trustedIpcMain as ipcMain } from './trusted-ipc'
import { readdirSync, statSync, existsSync, writeFileSync, mkdirSync } from 'fs'
import { join, relative, resolve } from 'path'
import { homedir } from 'os'
import { locateExecutable, readExecutableVersion } from '../utils/external-command'
import { IPC_CHANNELS } from '../../shared/ipc-types'
import { DiagnosticsService } from '../services/diagnostics'
import { getProjectRoot } from '../utils/paths'

// ─── Manifest of expected source files (relative to src/) ───
const SOURCE_MANIFEST = [
  'main/index.ts',
  'main/ipc/files.ts',
  'main/ipc/index.ts',
  'main/ipc/projects.ts',
  'main/ipc/settings.ts',
  'main/ipc/terminal.ts',
  'main/ipc/maintenance.ts',
  'main/services/claude-process.ts',
  'main/utils/paths.ts',
  'preload/index.ts',
  'renderer/App.tsx',
  'renderer/components/common/ContextMenu.tsx',
  'renderer/components/editors/MarkdownEditor.tsx',
  'renderer/components/editors/SkillViewer.tsx',
  'renderer/components/editors/SettingsEditor.tsx',
  'renderer/components/layout/AppShell.tsx',
  'renderer/components/layout/MainPanel.tsx',
  'renderer/components/layout/Sidebar.tsx',
  'renderer/components/layout/StatusBar.tsx',
  'renderer/components/layout/TerminalPanel.tsx',
  'renderer/components/tabs/TabBar.tsx',
  'renderer/components/tabs/WelcomeTab.tsx',
  'renderer/contexts/TabContext.tsx',
  'renderer/contexts/TerminalLayoutContext.tsx',
  'renderer/contexts/WorkspaceContext.tsx',
  'renderer/env.d.ts',
  'renderer/index.html',
  'renderer/main.tsx',
  'renderer/styles/globals.css',
  'shared/ipc-types.ts'
]

function getSourceDir(): string {
  return join(getProjectRoot(), 'src')
}

const EMPTY_FILE_TEMPLATES: Record<string, string> = {
  'ts': `// Auto-generated by integrity repair\n`,
  'tsx': `import { useState } from 'react'\n\nexport default function Component() {\n  return <div />\n}\n`,
  'css': `/* Auto-generated by integrity repair */\n`,
  'html': `<!DOCTYPE html>\n<html lang="zh-CN">\n<head><meta charset="UTF-8"/><title></title></head>\n<body></body>\n</html>\n`
}

export function registerMaintenanceHandlers(
  getRpStatus?: () => { mode: string; name?: string; sanitizedHost?: string }
): void {
  // ─── Integrity Check ───
  ipcMain.handle(IPC_CHANNELS.INTEGRITY_CHECK, async () => {
    const results: Array<{ file: string; status: 'ok' | 'missing' | 'empty'; size: number }> = []
    let missingCount = 0
    let emptyCount = 0

    for (const relPath of SOURCE_MANIFEST) {
      const fullPath = join(getSourceDir(), relPath)
      if (!existsSync(fullPath)) {
        results.push({ file: relPath, status: 'missing', size: 0 })
        missingCount++
      } else {
        const stats = statSync(fullPath)
        if (stats.size === 0) {
          results.push({ file: relPath, status: 'empty', size: 0 })
          emptyCount++
        } else {
          results.push({ file: relPath, status: 'ok', size: stats.size })
        }
      }
    }

    return {
      results,
      summary: {
        total: SOURCE_MANIFEST.length,
        ok: SOURCE_MANIFEST.length - missingCount - emptyCount,
        missing: missingCount,
        empty: emptyCount
      }
    }
  })

  // ─── Integrity Repair ───
  ipcMain.handle(IPC_CHANNELS.INTEGRITY_REPAIR, async () => {
    const repaired: string[] = []
    const errors: string[] = []

    for (const relPath of SOURCE_MANIFEST) {
      const fullPath = join(getSourceDir(), relPath)
      if (existsSync(fullPath) && statSync(fullPath).size > 0) continue

      try {
        // Ensure parent dir exists
        const dir = fullPath.split('\\').slice(0, -1).join('\\')
        if (!existsSync(dir)) {
          mkdirSync(dir, { recursive: true })
        }

        // Determine extension and create placeholder
        const ext = relPath.split('.').pop() || 'ts'
        const template = EMPTY_FILE_TEMPLATES[ext] || '// placeholder\n'
        writeFileSync(fullPath, template, 'utf-8')
        repaired.push(relPath)
      } catch (err) {
        errors.push(`${relPath}: ${err instanceof Error ? err.message : 'unknown error'}`)
      }
    }

    return { repaired, errors, count: repaired.length }
  })

  // ─── Detect Claude Code ───
  ipcMain.handle(IPC_CHANNELS.CLAUDE_DETECT, async () => {
    const paths: Array<{ path: string; exists: boolean; version?: string }> = []
    let foundPath: string | null = null
    let version: string | null = null

    // Common install locations
    const candidates = [
      join(homedir(), 'AppData', 'Roaming', 'npm', 'node_modules', '@anthropic-ai', 'claude-code', 'bin', 'claude.exe'),
      join(homedir(), 'AppData', 'Local', 'anthropic', 'claude', 'claude.exe'),
      'C:\\Program Files\\nodejs\\claude.exe',
      join(homedir(), 'AppData', 'Roaming', 'npm', 'claude.cmd'),
      join(homedir(), 'AppData', 'Roaming', 'npm', 'claude')
    ]

    for (const p of candidates) {
      const exists = existsSync(p)
      paths.push({ path: p, exists })
      if (exists && !foundPath) {
        foundPath = p
      }
    }

    // Try PATH detection without invoking a command shell.
    const located = locateExecutable('claude')
    const locatedPath = located.ok ? located.val.split(/\r?\n/)[0] : ''
    if (locatedPath) {
      paths.push({ path: `PATH: ${locatedPath}`, exists: true })
      if (!foundPath) foundPath = locatedPath
    }

    // Batch shims are reported as detected but are not executed through cmd.exe.
    if (foundPath) {
      const versionResult = readExecutableVersion(foundPath)
      if (versionResult.ok) version = versionResult.val
    }

    // Save detected path to workspace settings
    if (foundPath && version) {
      try {
        const claudeMdPath = join(getSourceDir(), 'main', 'utils', 'paths.ts')
        // Don't modify paths.ts, just return the result
      } catch { /* ignore */ }
    }

    return { paths, foundPath, version, found: foundPath !== null }
  })

  // ─── Diagnostics ───
  const diagnosticsService = new DiagnosticsService(getRpStatus)
  ipcMain.handle(IPC_CHANNELS.DIAGNOSTICS_RUN, async () => diagnosticsService.runAll())
  ipcMain.handle(IPC_CHANNELS.DIAGNOSTICS_LAST_REPORT, async () => diagnosticsService.getLastReport())
}
